default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['HEROKU_USERNAME'] %>
  password: <%= ENV['HEROKU_PWORD'] %>
  database: <%= ENV['HEROKU_DB'] %>
  host: <%= ENV['HEROKU_HOST'] %>
  PORT: <%= ENV['HEROKU_PORT'] %>
development:
  <<: *default




test:
  <<: *default
  database: <%= ENV['HEROKU_DB_URL'] %>

#
production:
  <<: *default
  url: <%= ENV['HEROKU_DB_URL'] %>
